<a href="https://colab.research.google.com/github/supermario64bit/scaler_ai_ml_resources/blob/main/day1_05_Dec_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **What is a model?**<br>
We  write algorithms(set of instructions) for solving problems. If an algorithm trained with historical data, patterns, trends and extra data. That algorithm is a model.


**Basic Data Preprocessing**<br>


1.   Extract the informations
2.   Fix the missing values
3.   Clean and fix the data type
4.   Feature Engineering (Create new features in the data using the existing dataset)

**Feature Engineering**<br>
Its a process to add new features to data so that we can train our model with more patterns.

# **NumPy**<br>
A python library which supports numerical operations and datasets where we can do vectorised and broadcasted operations. This property makes it distinct from python list. The ndArray in NumPy is the important datastructure where we do most of the operations. Here we supports vectorised and broadcasted operations and also the it is contegious memmory. But python list which has similar properties is not contegious but its references are arranged in contegious manner. Unlike python numpy ndArrays only accepts same type of data. The numpy is optimised in C programmin language which is a lower level programming language and this also makes the numpy performance faster.

# **What you mean by vectorized operations?**<br>
Consider the python list, if we need to multiply all the values inside the list means we need to run a loop and access each elements and then multiply and update the new value to the index.
<br>
Instead of doing this sequential operation, we can do it in single operation on entire arrays and the operation will broadcasted to all the array members simultaneosly. And that is vectorized operation
<br>
Python list didn't support vectorized operations but NumPy array does.

In [14]:
import numpy as np

# Food Delivery Data Exploration and analysis

# Votes for each of the restaurants
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

# Average cost for each of the restaurants
costs = np.array(["'800.0'" ,"'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'", "'600.0'", "'700.0'" ,"'550.0'", "'500.0'"])

print("Votes (Array):", votes)
print("Costs (Array):", costs)

Votes (Array): [ 775  787  918   88  166  286 2556  324  504  402]
Costs (Array): ["'800.0'" "'800.0'" "'800.0'" "'300.0'" "'600.0'" "'600.0'" "'600.0'"
 "'700.0'" "'550.0'" "'500.0'"]


**Lets analyse the data**<br>


1.   Votes are integers
2.   Costs are not floating values but in string format wrapped with single quotes charector

**Commands to check charecteristics of data**<br>
*Consider **arr** is a numpy array variable*

1. To check the shape of the array
```
arr.shape
```
2. To check the dimensions
```
arr.ndim
```

3. To check the size(number of elements)
```
arr.size
```



In [10]:
votes.shape #votes has 10 elements in the x axis and since its a 1D array no y axis exists

(10,)

In [11]:
votes.ndim # Votes is single dimensional array

1

In [12]:
votes.size # Vote has 10 elements

10

# **Data Manipulation**
We have votes and cost of respected restaurants as 1D array.

1. We can convert them into a 2d array using:


```
np.array([votes, costs])
```
2. We can create an array with specified range:


```
np.arange(1,5)
```




In [17]:
np.array([votes, costs])

array([['775', '787', '918', '88', '166', '286', '2556', '324', '504',
        '402'],
       ["'800.0'", "'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'",
        "'600.0'", "'700.0'", "'550.0'", "'500.0'"]], dtype='<U21')

In [19]:
np.arange(1,5) # Create an array between 1 to 4 and 5 is excluded

array([1, 2, 3, 4])

In [21]:
np.arange(1,9,2) #Create an array from 1 to 8 by skipping 2 numbers.

array([1, 3, 5, 7])

3. In our costs, the data is available in string and it cannot convert directly to float because of the single inverted comma symbol present in the string. So first we will remove the symbol and then we can convert directly to float.
<br>
To remove symbol:


```
np.char.replace(costs, "'", "")
```

To convert to float:


```
costs.astype(float)
```





In [27]:
cleaned_costs = np.char.replace(costs, "'", "")

In [30]:
cleaned_costs = cleaned_costs.astype(float)

# **Accesing Array Data With Index**

To get a single element in index i, we can use:
```
cleaned_costs[i]
```

To get elements from reverse order user negative indexing:
```
cleaned_costs[-i]
```
To get elements in multiple index as array, we can use:
```
cleaned_costs[1,3,4]
```
To slice the array with index:
```
cleaned_costs[1:3]
```
To filter data with some condition
```
cleaned_costs[cleaned_costs > 200]
```

In [31]:
cleaned_costs[1] # To get second element

np.float64(800.0)

In [32]:
cleaned_costs[-1] # To get last element

np.float64(500.0)

In [36]:
cleaned_costs[[0,2,3]] # To get elements in the index 0,2,3 as array

array([800., 800., 300.])

In [39]:
cleaned_costs[1:3] # Slice elements from 1 to 3 index, 3 is excluded

array([800., 800.])

In [44]:
cleaned_costs[cleaned_costs < 500] # Get elements less than 500

array([300.])

# **Data Masking**
We can mask the data using true or false with a condition. It will check the condition as a vectorized operation and mask the data with true or false according to the decision.



```
cleaned_costs > 500
```


In [40]:
cleaned_costs > 500 # It will mask True for the values greater than 500 and rest mask with False

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
       False])