<a href="https://colab.research.google.com/github/supermario64bit/scaler_ai_ml_resources/blob/main/day2_08_Dec_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Function That Numpy Can Perform**


*   While creating NumPy array, it will accept data with multiple types, numpy will automatically convert all to the safest datatype to accomodate all values as same datatype to maintain the array property.


```
mixed_data = np.array([100,'200', 300.5, 'Hundred'])
```
The above code won't raise any error. It will create a numpy array with string datatype(safest datatype to accomodate all values)


In [79]:
np.array([100,'200', 300.5, 'Hundred']) # Gives Array of strings

array(['100', '200', '300.5', 'Hundred'], dtype='<U32')



*   **Column Stack**<br>


---


Column stack is used to stack 1-D arrays as columns and convrt it into a single 2-D array


```
np.column_stack(array1, array2)
```
The above function will return a 2-D array with array1 as column1 and array2 as column 2, if they are 1D array

> Add blockquote






In [80]:
#sample of 50 restaurants

sample_votes = np.array([775, 787, 918, 88, 166, 286, 2556, 324, 504, 402, 150, 164, 424, 918, 90, 133, 144, 93, 62, 180, 62, 148, 219, 506, 172, 415, 230, 1647, 4884, 133, 286, 540, 2556, 36, 244, 804, 679, 245, 345, 618, 1047, 627, 354, 244, 163, 808, 1720, 868, 520, 299])
sample_costs = np.array([800.0, 800.0, 800.0, 300.0, 600.0, 600.0, 600.0, 700.0, 550.0, 500.0, 600.0, 500.0, 450.0, 800.0, 650.0, 800.0, 700.0, 300.0, 400.0, 500.0, 600.0, 550.0, 600.0, 500.0, 750.0, 500.0, 650.0, 600.0, 750.0, 200.0, 500.0, 800.0, 600.0, 400.0, 300.0, 450.0, 850.0, 300.0, 400.0, 750.0, 450.0, 450.0, 800.0, 800.0, 800.0, 850.0, 400.0, 1200.0, 300.0, 300.0])

restaurants_data = np.column_stack((sample_votes, sample_costs)) # Creating 2d array from two 1D array using column_stack
restaurants_data #2d array

array([[ 775.,  800.],
       [ 787.,  800.],
       [ 918.,  800.],
       [  88.,  300.],
       [ 166.,  600.],
       [ 286.,  600.],
       [2556.,  600.],
       [ 324.,  700.],
       [ 504.,  550.],
       [ 402.,  500.],
       [ 150.,  600.],
       [ 164.,  500.],
       [ 424.,  450.],
       [ 918.,  800.],
       [  90.,  650.],
       [ 133.,  800.],
       [ 144.,  700.],
       [  93.,  300.],
       [  62.,  400.],
       [ 180.,  500.],
       [  62.,  600.],
       [ 148.,  550.],
       [ 219.,  600.],
       [ 506.,  500.],
       [ 172.,  750.],
       [ 415.,  500.],
       [ 230.,  650.],
       [1647.,  600.],
       [4884.,  750.],
       [ 133.,  200.],
       [ 286.,  500.],
       [ 540.,  800.],
       [2556.,  600.],
       [  36.,  400.],
       [ 244.,  300.],
       [ 804.,  450.],
       [ 679.,  850.],
       [ 245.,  300.],
       [ 345.,  400.],
       [ 618.,  750.],
       [1047.,  450.],
       [ 627.,  450.],
       [ 354.,  800.],
       [ 24



*   **Array reshape**<br>


---


NumPy allows to reshape the existing array to a different shape. But the only concern is we need to maintain the same size of the existing array while reshaping. Other wise it will throw an error.

To reshape an array the code is:
```
array.reshape(x,y)
```





In [81]:
restaurants_data.shape

(50, 2)

In [82]:
restaurants_data.reshape(25,4) # restaurants_data has 100 elements so 25 rows and 4 column matrix is enough to maintain 100 elements. we can also do (10,10)

array([[ 775.,  800.,  787.,  800.],
       [ 918.,  800.,   88.,  300.],
       [ 166.,  600.,  286.,  600.],
       [2556.,  600.,  324.,  700.],
       [ 504.,  550.,  402.,  500.],
       [ 150.,  600.,  164.,  500.],
       [ 424.,  450.,  918.,  800.],
       [  90.,  650.,  133.,  800.],
       [ 144.,  700.,   93.,  300.],
       [  62.,  400.,  180.,  500.],
       [  62.,  600.,  148.,  550.],
       [ 219.,  600.,  506.,  500.],
       [ 172.,  750.,  415.,  500.],
       [ 230.,  650., 1647.,  600.],
       [4884.,  750.,  133.,  200.],
       [ 286.,  500.,  540.,  800.],
       [2556.,  600.,   36.,  400.],
       [ 244.,  300.,  804.,  450.],
       [ 679.,  850.,  245.,  300.],
       [ 345.,  400.,  618.,  750.],
       [1047.,  450.,  627.,  450.],
       [ 354.,  800.,  244.,  800.],
       [ 163.,  800.,  808.,  850.],
       [1720.,  400.,  868., 1200.],
       [ 520.,  300.,  299.,  300.]])

In [83]:
restaurants_data.reshape(10,10)

array([[ 775.,  800.,  787.,  800.,  918.,  800.,   88.,  300.,  166.,
         600.],
       [ 286.,  600., 2556.,  600.,  324.,  700.,  504.,  550.,  402.,
         500.],
       [ 150.,  600.,  164.,  500.,  424.,  450.,  918.,  800.,   90.,
         650.],
       [ 133.,  800.,  144.,  700.,   93.,  300.,   62.,  400.,  180.,
         500.],
       [  62.,  600.,  148.,  550.,  219.,  600.,  506.,  500.,  172.,
         750.],
       [ 415.,  500.,  230.,  650., 1647.,  600., 4884.,  750.,  133.,
         200.],
       [ 286.,  500.,  540.,  800., 2556.,  600.,   36.,  400.,  244.,
         300.],
       [ 804.,  450.,  679.,  850.,  245.,  300.,  345.,  400.,  618.,
         750.],
       [1047.,  450.,  627.,  450.,  354.,  800.,  244.,  800.,  163.,
         800.],
       [ 808.,  850., 1720.,  400.,  868., 1200.,  520.,  300.,  299.,
         300.]])

**Note**
> In machine learning the datas we recieve mostly in csv, excel format. Those datas are in tabular form, where table is a 2D matrix. But in this 2D matrix each columns can be considered as dimensions.



**Transpose in NumPy**<br>


---


Transpose is used to convert rows into columns or columns into rows. Otherwise we can say like, it is used to reverse the shape. For example if shape is (x,y) after transpose the shape will be(y,x)


We can perform transpose using two ways,


1.   1st Way
```
arr.T
```
2.   2nd Way


```
arr.transpose()
```




In [84]:
restaurants_data.transpose()

array([[ 775.,  787.,  918.,   88.,  166.,  286., 2556.,  324.,  504.,
         402.,  150.,  164.,  424.,  918.,   90.,  133.,  144.,   93.,
          62.,  180.,   62.,  148.,  219.,  506.,  172.,  415.,  230.,
        1647., 4884.,  133.,  286.,  540., 2556.,   36.,  244.,  804.,
         679.,  245.,  345.,  618., 1047.,  627.,  354.,  244.,  163.,
         808., 1720.,  868.,  520.,  299.],
       [ 800.,  800.,  800.,  300.,  600.,  600.,  600.,  700.,  550.,
         500.,  600.,  500.,  450.,  800.,  650.,  800.,  700.,  300.,
         400.,  500.,  600.,  550.,  600.,  500.,  750.,  500.,  650.,
         600.,  750.,  200.,  500.,  800.,  600.,  400.,  300.,  450.,
         850.,  300.,  400.,  750.,  450.,  450.,  800.,  800.,  800.,
         850.,  400., 1200.,  300.,  300.]])

In [85]:
restaurants_data.T

array([[ 775.,  787.,  918.,   88.,  166.,  286., 2556.,  324.,  504.,
         402.,  150.,  164.,  424.,  918.,   90.,  133.,  144.,   93.,
          62.,  180.,   62.,  148.,  219.,  506.,  172.,  415.,  230.,
        1647., 4884.,  133.,  286.,  540., 2556.,   36.,  244.,  804.,
         679.,  245.,  345.,  618., 1047.,  627.,  354.,  244.,  163.,
         808., 1720.,  868.,  520.,  299.],
       [ 800.,  800.,  800.,  300.,  600.,  600.,  600.,  700.,  550.,
         500.,  600.,  500.,  450.,  800.,  650.,  800.,  700.,  300.,
         400.,  500.,  600.,  550.,  600.,  500.,  750.,  500.,  650.,
         600.,  750.,  200.,  500.,  800.,  600.,  400.,  300.,  450.,
         850.,  300.,  400.,  750.,  450.,  450.,  800.,  800.,  800.,
         850.,  400., 1200.,  300.,  300.]])

**Indexing through columns in NumPy 2D Array**<br>


---


If we have a 2D data and we need the column wise data for first 10 indexes we can use the column wise indexing feature of NumPy. The syntax for the same is:


```
arr[:10,0]
```
After comma we need to give the index of column.



In [86]:
restaurants_data[:10,0] # First column of the first 10 datas in the restaurant_data

array([ 775.,  787.,  918.,   88.,  166.,  286., 2556.,  324.,  504.,
        402.])

In [87]:
# Extracting from 2D and creating 1D arrays
all_votes = restaurants_data[:,0] #Getting all the votes using the column wise indexing
all_costs = restaurants_data[:,1] #Getting all the costs using the column wise indexing

In [88]:
# Getting the mathematical operations from array using NumPy way(Vectorised and Broadcasted operations)\
print(np.sum(all_votes)) #Sum of all votes
print(np.mean(all_votes)) #mean of all votes
print(np.min(all_votes)) #minimum from all votes
print(np.max(all_votes)) #maximum from all votes

30583.0
611.66
36.0
4884.0


**Filtering Data**


---


To filter the data we can use where function in NumPy array. But we have some other functions to check specific conditions. They are:



1.   np.any(condition_here)
*any* function returns boolean value. If the given condition satisfy any of the data in the array it will return true, otherwise it will return false.

For checking the all_costs has any cost which is greater than 500:
```
np.any(all_costs > 500)
```


2.   np.all(condition_here)
*all* function also returns boolean value. If the given condition is satosfied by all the datas in the array, the function will return true. Otherwise it always return false.

For checking the all_costs has all the cost which is greater than 500:
```
np.all(all_costs > 500)
```

In [89]:
print(np.any(all_costs > 500))

True


In [90]:
print(np.all(all_costs > 500))

False


**Sorting Data By Rows & Columns**<br>


---

Row wise sorting:


```
np.sort(array, axis=0)
```
Here axis 0 refers rows


---


Column wise sorting:


```
np.sort(array, axis=1)
```
Here axis 1 refers column

In [91]:
##### Sample 2D array ######

numeric_data = np.array([
    [4.1, 775.0, 800.0],
    [3.8, 787.0, 800.0],
    [4.0, 918.0, 800.0],
    [2.6, 88.0, 300.0],
    [1.1, 166.0, 600.0],
    [3.5, 286.0, 600.0],
    [4.7, 2556.0, 600.0],
    [2.5, 324.0, 700.0],
    [2.8, 504.0, 550.0],
    [3.4, 402.0, 500.0]
])

# Set print options to suppress scientific notation
np.set_printoptions(suppress=True, precision=1)

In [92]:
#SORT IN ASCENDING ORDER ALONG THE ROWS

np.sort(numeric_data, axis=0)

array([[   1.1,   88. ,  300. ],
       [   2.5,  166. ,  500. ],
       [   2.6,  286. ,  550. ],
       [   2.8,  324. ,  600. ],
       [   3.4,  402. ,  600. ],
       [   3.5,  504. ,  600. ],
       [   3.8,  775. ,  700. ],
       [   4. ,  787. ,  800. ],
       [   4.1,  918. ,  800. ],
       [   4.7, 2556. ,  800. ]])

In [93]:
# Consider column 1 contains ratings and extract the rating

ratings = numeric_data[:,0]
ratings

array([4.1, 3.8, 4. , 2.6, 1.1, 3.5, 4.7, 2.5, 2.8, 3.4])

**Getting Indices of array element in sorted order**


---


NumPy has a way to get the array of index in sorted order after sorting. For that we use *argsort* function for this purpose.



```
np.argsort(ratings)
```
It will sort the array and return the indexes in the ascending order of elements.


In [94]:
np.argsort(ratings) #Array of indices in sorted order

array([4, 7, 3, 8, 9, 5, 1, 2, 0, 6])

**Maximum and Minimum value index in NumPy**


---



To get the index of minimum value of the array we use *argmin*.


```
np.argmin(array)
```

To get the index of maximum value of the array we use *argmin*.


```
np.argmax(array)
```

In [95]:
print(np.argmin(ratings)) # Index of minimum rating

4


In [96]:
print(np.argmax(ratings)) # Index of maximum rating

6


**Maths Operations in Numpy Metrices**


---

1.   Multiplication
We use `@` symbol for multiplying two matrices.


```
matrix1 @ matrix 2
```

In [97]:
# Lets create two random matrix to multiply
x = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
y= np.arange (3,12).reshape(3,3)

In [98]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
y

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [100]:
# Multiply two matrix
x @ y

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

**Vctorize a python function**


---


If we have a function and need to pass the array elements to the function, normally we use loops to do that. If the elements are in numpy array we can simply vectorize the entire function and simply pass the array to the function. To convert a function to a vectorized function we use:


```
vectorized_def = np.vectorize(def_name)
```
vectorized_def can perform the same function in vectorized operation.



In [101]:
# A normal function to get discounted cost

def discount_cost(rate, cost):
    """Apply a 10% discount if the rating is 4.0 or higher."""
    if rate >= 4.0:
        return cost * 0.9
    else:
        return cost

In [102]:
# Getting the rating and costs from the sample numeric_data initialized before
rating = numeric_data[:, 0]
cost = numeric_data[:, 1]

In [103]:
# Vectorizeing the discount function
vectorized_discount_cost = np.vectorize(discount_cost)

In [104]:
# Performing vectorized function operation
vectorized_discount_cost(rating, cost)

array([ 697.5,  787. ,  826.2,   88. ,  166. ,  286. , 2300.4,  324. ,
        504. ,  402. ])